### PR TITLE
Add README info for environment param

### PR DESCRIPTION
**Pull request by everestx**
Per request from #24 here are some additions to the README for using the `$environment` parameter for custom environments.

### CODE REVIEW

**Comment by everestx** [comment]
Also, if this is works can you bump the puppet forge version?  I'm running into #9 when trying to use librarian-puppet with a :git sha reference.

**Comment by everestx** [comment]
Take a look at that last commit, since I've remove some things from `Puppetfile` and `Puppetfile.lock`.  I've tested librarian-puppet with those changes.  In essence, they just prevent and conflicts between `Puppetfile` and `metadata.json`

**Comment by everestx** [comment]
I've been thinking about this more over the past day and I'm not sure we want to mess with the Puppetfile.lock and Puppetfile at this time. I've removed that commit from my branch.  I think it's better to handle the versions in those files via a separate issue or PR.

**Comment by justindowning** [comment]
Thanks for coming back to document! I'll cut a new release today or tomorrow. As for the metadata & Puppetfile, I try to leave well enough alone. So, unless we need to adjust deps or something related, we can probably just leave it.

**Comment by everestx** [comment]
Hi @justindowning, just a friendly reminder to cut a version update on puppet forge. Thanks.

**Comment by justindowning** [comment]
@everestx D'oh! Sorry for forgetting! I just cut `2.5.0` and released to the Forge: https://forge.puppetlabs.com/jdowning/statsd

**Pull request merged**
